services:
    handbrake:
        container_name: handbrake
        image: jlesage/handbrake
        restart: unless-stopped
        ports:
            - 5800:5800
        volumes:
            - ./appdata:/config:rw
            - /mnt/media/handbrake/watch:/watch:rw
            - /mnt/media/handbrake/output:/output:rw